"use clinet";
import AddLocation from "./components/AddLocationForm";
import "./globals.css";
import Home from "./pages";
import AssetsPage from "./pages/assets";
import AssetHistory from "./pages/history";
import TransferAsset from "./pages/transfer";



export const metadata = {
  title: "Asset Management Software",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className=" selection:bg-green-600  selection:text-gray-200"
      >

        {children}

        <AssetsPage />
        {/* <AssignAssetForm /> */}

        <AddLocation />
        <TransferAsset />
        <AssetHistory />

        <Home />
      </body>
    </html>
  );
}
